lib/modules/groupsHelpers.js, services/auth/lib/handlers.js, services/auth/lib/local.js, services/auth/lib/modules/queryBuilder.js, services/docs/lib/handlers.js, services/docs/lib/modules/permissions.js, services/docs/lib/modules/queryBuilder.js, services/docs/lib/param.js, services/docs/lib/services/document.js
For all documents in docs.vault.* collections, groups added on creation/deletion.
A user can access any document that has at least one common group with him
The usual access check based on user role by state is still working
=> Groups access to vault documents

package-lock.json, services/docs/lib/services/document.js
if query.with contains creator and/or parentId, those are returned in the response
=> getDocuments pipeline updated to include creator and/or parentId if specified in query

.gitignore, services/auth/lib/handlers.js
=> allow email update in updateMe function

services/auth/lib/handlers.js, services/auth/lib/index.js
to complete [PR #49 ](https://github.com/campsi/campsi-mono/pull/49)
Just a way to patch a user. It works exactly like docs service patch
=> PATCH route added to auth service

services/docs/lib/modules/embedDocs.js
to resolve `cannot get property states of null`
=> fix: embed not found resulting in error

lib/modules/responseHelpers.js, lib/server.js, package-lock.json, package.json, services/assets/lib/handlers.js, services/auth/lib/handlers.js, services/auth/lib/index.js, services/docs/lib/handlers.js, services/docs/lib/index.js, services/docs/lib/modules/queryBuilder.js, services/docs/lib/services/resource.js, services/trace/lib/handlers.js
Just felt like removing it, it was not too widely used
=> refactor: for-in dependency removed

services/versioned-docs/lib/services/user.js
=> fix: versioned docs users not returned

lib/server.js, lib/service.js
the services dict becomes a Map but have not been changed in describe function
=> Fix describe 

services/stripe-billing/lib/index.js
=> feat: add fetchCreditNotes to billing service

services/versioned-docs/lib/param.js
just a tiny harmless refactor of this function, but that allows me to use `attach`  externally (to use it in a middleware, mainly to complete req actually)
=> refactor: attachResource for external usage

services/stripe-billing/lib/index.js
Just a route to return customers list, with optional params according to [Stripe API doc](https://stripe.com/docs/api/customers/list?lang=node).
Note: I've forced `email.toLowerCase()` for more consistency
=> feat: route to get stripe customers list

services/docs/lib/modules/permissions.js
Public resources could not be fetched when the user was authenticated.
=> Fix logic of the can function

lib/modules/findReferences.js, package.json, services/auth/test/config/test.js, services/docs/lib/modules/embedDocs.js, services/docs/test/config/options/docs.js, services/docs/test/config/test.js, services/docs/test/embed.js, services/trace/test/config/test.js, services/webhooks/test/config/test.js
Fix embed docs for array
Add & repair some tests
=> AXE-556 Embed array of sub docs

services/assets/lib/services/asset.js, services/docs/lib/handlers.js, services/docs/lib/modules/queryBuilder.js, services/docs/test/filters.js
=> Add filters to doc service

lib/modules/createObjectId.js, lib/modules/findReferences.js, services/docs/lib/modules/embedDocs.js, test/docs/embed.js
Fix a bug in FindReferences
Fix a bug in createObjectId
=> Fix Campsi crash on getDocs (embed error)

services/docs/lib/param.js, services/versioned-docs/lib/param.js
Reverts campsi/campsi-mono#104
=> Revert "refactor: docs service attachResource refactored for external usage"

services/docs/lib/modules/permissions.js, services/docs/lib/param.js
forgot to refactor can function (was a promise)
=> refactor: docs service attachResource refactored for external usage

services/stripe-billing/lib/index.js
title self explanatory
usage records is used for metered billing
=> feat: stripe createUsageRecord added to billing service

.husky/pre-commit, services/stripe-billing/lib/index.js
title self explanatory. needed to fix a bug in caas-styleguide
Note: tests on precommit disabled since they fail
=> feat: add some stripe PaymentIntent features

services/stripe-billing/lib/index.js
title self-explanatory (stripe related)
=> feat: return list of usage records summaries

services/auth/lib/local.js
Fix broken invitation resulting in "A user already exists with that email" error message.
Can't test it, caas-api is broken when I try to run it with `npm link campsi` ☹️
=> fix: broken invitation (AXE-1137)

services/stripe-billing/lib/index.js
stripe expand param added almost everywhere for more consistency
=> feat: expand stripe expand

services/stripe-billing/lib/index.js
=> feat: handle body for stripe subscription delete params

package.json, services/notifications/index.js, test/config/test.js, test/notifications/notifications.js
This PR initializes the new notifications service
=> [Campsi-mono] - Add init notifications service

services/auth/lib/handlers.js
This PR adds a new attr on the user. The `lastSeenAt` will use to know the date of last interaction of our users with our back-office
=> [Campsi-mono] - Add lastSeenAt on the /me

services/auth/lib/local.js, services/auth/lib/modules/queryBuilder.js, services/auth/lib/providers/facebook.js, services/auth/lib/providers/google.js
Save country when user register with Google.
Facebook didn't authorize us to get Location from the user, so i set the country on France by default.
=> [CAMPSI-MONO] - Save country from Google

services/docs/lib/services/document.js
Correct error handling in the promise returned in the function getDocumentLinks.
=> correct error handling in promise

package-lock.json, package.json, services/notifications/handlers.js, services/notifications/index.js, services/notifications/param.js, test/notifications/crud.js, test/schemas/notification.schema.json
This is the first PR for the CRUD notification. This is a very basic CRUD data validation only. User validation and other feature will come very soon in other PR.
=> [Campsi-mono] CRUD notifications

services/auth/lib/handlers.js
Trigger every time the same payload on invitation created.
=> [Campsi-Mono] - Update handlers.js

services/stripe-billing/lib/index.js
we used to set `fr-FR` as default locale, not anymore
=> feat: stripe customer preferred-locale changed

services/stripe-billing/lib/index.js
=> feat: higher stripe max retries

services/auth/lib/handlers.js, services/auth/lib/index.js, test/auth/auth.js
Goal of the PR was to extract personal data from the auth service belonging to a user.
=> added route to extract personal data from the auth service

test/github-test/empty.js
PR to test github actions release flow
=> fix: this is dummy fix to test gh actions

package-lock.json
package-json lock file needed updating
=> fix: lock file updated

services/stripe-billing/lib/index.js
title self-explanatory: new route added to return next stripe invoice
=> feat: add get next invoice stripe route

services/stripe-billing/lib/index.js
=> feat: adding some stripe subscriptionSchedules related routes

.eslintrc, .prettierrc, package-lock.json, package.json
Goal of this PR was to remove the eslint and prettier configuration from the project and use the elsint and prettier configuration in the eslint-config-axeptio package instead
=> feat: use axeptio eslint package

services/docs/lib/modules/embedDocs.js
if document?.[_id] is undefined => remove the _id
=> fix: subdocument _id undefined

services/stripe-billing/lib/index.js
=> feat: plug stripe errors to campsi logger (DEV-2651)

services/stripe-billing/lib/index.js
same regex used in caas-styleguide
=> fix: faulty regex to validate email (DEV-2709)

services/stripe-billing/lib/index.js
=> feat: less strict stripe idempotency key

services/docs/lib/services/document.js
Reverts campsi/campsi-mono#198
=> Revert "feat: add metadata to getDocument if available"

services/docs/lib/services/document.js
=> feat: add metadata to getDocument (DEV-3000)

services/auth/lib/handlers.js, services/auth/lib/index.js, services/docs/lib/handlers.js, services/docs/lib/services/document.js, services/docs/lib/services/userService.js, services/versioned-docs/lib/handlers.js, services/versioned-docs/lib/services/userService.js, test/auth/auth.js, test/config/test.js, test/docs/config/options/docs.js, test/docs/events.js, test/docs/owner.js, test/versioned-docs/versioned-docs.js
Reverts campsi/campsi-mono#165
=> Revert "Jameslotery/dev 2017"

services/auth/lib/handlers.js
=> fix: undefined softDelete export removed

services/auth/lib/handlers.js
function was missing, probably lost during a messed up merge
=> fix: softDelete restored

lib/server.js
=> feat: loadServices refactored/clarified

lib/server.js, services/trace/lib/index.js, services/webhooks/lib/index.js
=> feat: refactor old syntax causing hard to debug issues

lib/modules/createObjectId.js
=> feat: refined createObjectId function

lib/modules/paginateCursor.js
=> chore: JSdoc precisions for paginateQuery

services/assets/lib/services/asset.js
was removed by mistake during pagination refactoring
=> fix: allow assets pagination infinite (DEV-3127)

services/docs/lib/services/document.js, services/versioned-docs/lib/services/document.js
has been removed by mistake during refactoring
=> fix: allow pagination infinite for paginateQuery

lib/modules/paginateCursor.js
=> feat: allow passing options to paginateQuery

services/audit/index.js, services/audit/services/journal.js, services/audit/utils.js, test/audit/service_creation.js, test/config/test.js
I try this new service in caas-api and there are some little issues. So I fixed in this PR.
=> [Campsi-Mono] Fix: all issues after integration in caas-api

lib/modules/paginateCursor.js
=> feat: allow count bypass in pagination

services/auth/lib/handlers.js, services/auth/lib/providers/facebook.js, services/auth/lib/providers/github.js, services/auth/lib/providers/google.js, services/auth/lib/providers/local.js
A function `validateRedirectURI` can be passed as provider option.
If this option exists, this function will be called during signin process
=> feat: allows validating redirectURI for auth callback (actual signin) (DEV-3395)

services/stripe-billing/lib/index.js
=> feat: allow a higher stripe maxNetworkRetries

services/auth/lib/local.js
=> fix: disable reset password for non local identity providers (DEV-3563)

services/auth/lib/handlers.js, services/auth/lib/index.js, services/docs/lib/handlers.js, services/docs/lib/param.js, services/docs/lib/services/document.js, services/versioned-docs/lib/handlers.js, services/versioned-docs/lib/param.js, services/versioned-docs/lib/services/document.js
- POST /auth/me/groups removed
- groups removed from invitation
- groups removed from req
- groups (req.groups) removed from doc creation
=> fix: groups security issues (DEV-3603)

services/auth/lib/index.js
=> fix: validate password reset url (DEV-3610)

services/stripe-billing/lib/index.js
added a middleware on every stripe routes
=> feat: secure stripe routes access (DEV-3681)

services/auth/lib/handlers.js, services/auth/lib/index.js
and cleanup expired invitations
=> feat: delete invitation (DEV-3678)

services/docs/lib/handlers.js
for audit purposes, add old doc data to document events (and complete new doc data for /patched events)
=> feat: add old doc data to document events (DEV-3665)

services/docs/lib/handlers.js, services/docs/lib/index.js
=> feat: emit document/creating event

services/docs/lib/handlers.js, services/versioned-docs/lib/handlers.js
`originalDocData` added to `document/deleted` and `versionedDocument/deleted` events
=> feat: improve deleted events (DEV-3823)

services/stripe-billing/lib/index.js
=> feat: allow expand for stripe next invoice

services/docs/lib/index.js, services/stripe-billing/lib/index.js, services/versioned-docs/lib/index.js
allows write access validation on docs and versioned docs services, through an optional middleware defined in service config
=> fix: validate docs write access (DEV-4175)

services/docs/lib/services/document.js
related to https://www.notion.so/axeptio/2023-10-05-CaaS-API-Hors-Service-d2453ae970b244658aa9220df55acc5a
=> fix: allowDiskUse missing from getDocuments (DEV-4503)

services/auth/lib/handlers.js, services/auth/lib/index.js
=> fix: redirectURI not properly working with local provider (DEV-4409)

services/audit/index.js
=> feat: add TTL index option for audit service (DEV-4323)

services/auth/lib/local.js
=> feat: allow to create a password reset token without a HTTP request

services/auth/lib/local.js
=> fix: this.updateUserWithPasswordResetToken is not a function in local.js (not arrow function)

services/stripe-billing/lib/index.js
=> feat: add currency to subscription creation payload

services/docs/lib/services/document.js
=> feat: allow returning metadata for getDocuments (DEV-5306)

lib/server.js, package-lock.json, package.json, services/auth/lib/handlers.js, services/auth/lib/local.js, services/auth/lib/passportMiddleware.js, services/docs/lib/services/document.js, services/notifications/handlers.js, services/versioned-docs/lib/services/document.js, services/webhooks/lib/index.js, test/auth/auth-local-passwordRegex.js, test/auth/auth-local.js, test/auth/auth.js, test/auth/delete.js, test/config/test.js, test/docs/lock-document.js, test/docs/soft-delete.js, test/helpers/setupBeforeEach.js
BREAKING CHANGE : due to v5 => v6 breaking changes updates:
- `findOneAndX` with implicit `{ includeResultMetadata: false }` (returns value)
unit tests fixed
=> feat: upgrade mongodb node driver (DEV-4642)

services/docs/lib/modules/queryBuilder.js, test/docs/filters.js
provide the possibility to filter on an array of numbers e.g. ?data.iabId[in]=10000,10001,10002
=> feat: Add 'in' operator for Numbers

services/auth/lib/local.js
self-explanatory (see comment)
=> fix: more accurate error message for createResetPasswordToken (DEV-5748)

services/docs/lib/handlers.js, services/docs/lib/index.js, services/docs/lib/param.js, services/docs/lib/services/document.js, test/docs/crud.js, test/docs/document-links.js, test/docs/embed.js, test/docs/filters.js
feat: add the possibility to filter by array of ids
feat: add custom verbs permissions
=> Filter by ids

services/docs/lib/modules/queryBuilder.js
Exports query filters to be used in our API
=> feat: add exports

README.md, lib/service.js, services/stripe-billing/lib/index.js
- add express error handler for each service
- add custom error handler for billing service
=> Achalhii/dev 6251/add services error handler

services/stripe-billing/lib/index.js
=> fix: customer default_source can't be unset

services/docs/lib/handlers.js
=> fix: put specific state

services/auth/lib/handlers.js, services/auth/lib/local.js
- allow firstName & lastName as root properties for user
- emit an event on user patch
=> feat: allow new props for user update (DEV-6651)

services/auth/lib/handlers.js
same as https://github.com/campsi/campsi-mono/pull/304 but for PUT update on user
=> feat: new props allowed on user update and event emitted (DEV-6604)

services/auth/lib/handlers.js
=> feat: add user to user update/patch event payload

services/auth/lib/index.js
=> fix: incomplete condition

package-lock.json, package.json, services/docs/lib/modules/queryBuilder.js, services/docs/lib/services/document.js, test/docs/validation.js
add the possibility to patch a doc with a required value in his schema
=> fix: patch docs with required value in schema

services/auth/lib/handlers.js
=> fix: update user updatedAt on PUT/PATCH on user (DEV-6740)

services/auth/lib/handlers.js
=> fix: incomplete  in tokens maintenance

services/docs/lib/services/document.js
Adds the idea of document plugins, a middleware that operates on the json document.
We are using this to ensure that some defaults are set in documents.
=> Add plugins to documents.  Doesn't apply to PATCH method.

services/auth/lib/local.js
Log original errors, and reply either with a 'fake' success code, or a more generic error.
=> fix: Log original errors, and reply either with a 'fake' success code,

services/auth/lib/handlers.js, services/auth/lib/index.js, services/auth/lib/local.js
Also remove user's password from error logs when the bcrypt compare fails.
BREAKING CHANGE
=> fix: check current password in the update password endpoint

services/stripe-billing/lib/index.js
see https://docs.stripe.com/api/subscriptions/cancel
=> feat: allow more infos in stripe subscription cancellation (ENG-7709)
