- services/stripe-billing/lib/index.js
instead of subscriptionId only
Note: `fetchInvoices` is the real part of the code that has been modified. The other changes are Prettier/ESlint related.
> refacto stripe fetchInvoices to pass any valid parameter

- services/auth/lib/handlers.js
- services/auth/lib/modules/queryBuilder.js
- services/docs/lib/services/document.js
and some fixes for invitedBy property being always null in DB
Sorry about the ESlint/Prettier changes polluting the diff. 
Real changes are on `addUserToDocument` and anything with `invitedBy` in it. 
I don't know how , but it would be nice to apply consistent ESlint/Prettier rules to all the project files and across our other projects to avoid this kind of annoyance.
> refacto add user to document to avoid 'users' collection property being overwritten when this route is hit simultaneously for the same document

- .gitignore
- services/docs/lib/modules/queryBuilder.js
- test/assets.js
- test/auth-fetch-users.js
- test/auth-index.js
- test/auth-local.js
- test/auth-unit.js
- test/auth.js
- test/docs-build-patch-query.js
Notes:
`npm test` was crashing because of bugs (it did even before I add my test). I've tried to fix them, but now it just exits. Probably because the first one (`Assets API /GET/`) is failing (see below)?
Most of the existing tests are working fine now, I've run them with [Wallaby.js](https://wallabyjs.com). They're all passing, except for those:
- `Assets API /GET/` . I don't understand why. It passes in debug mode if I add a breakpoint at the end of `createAsset`
- `Auth Local API /GET local/validate [default]`. It seems to be "normal" for this one (see line 192)
> unit test for queryBuilder patch function

- services/auth/lib/handlers.js
encryptedPassword was sent back to user related requests in `identities.local.encryptedPassword`
> Note: For now, user updates are done with PUT and not PATCH in caas-styleguide. => I'll make another branch to add PATCH to auth service. Because the complete user is sent as payload, stripped out of encryptedPassword so the user is updated into DB without any password.
> remove encrypted password from response

- services/docs/lib/modules/queryBuilder.js
As discussed, including the empty string value in $unset case create issues, we should use the $set operator.
> Use set operator for patch with empty string value

- services/docs/lib/handlers.js
- services/docs/lib/modules/embedDocs.js
- services/docs/lib/services/document.js
fetching relations was planned on campsi but was not working and never finished.
I finished it and cleaned up a little.
For this to work, you have to add a `rel` property when you define resources, for instance:
```javascript
projects: {
label: 'project',
class: 'versionedEntry',
schema: require('./schemas/project.schema'),
rels: {
organization: {
path: 'organizationId',
resource: 'organizations',
fields: ['companyName', 'subscription', '_id']
}
}
}
```
and adding `resources` in the schema, for instance:
```json
"resources": [
"organizations"
]
```
> Fix embed relationships subdocs

- services/docs/lib/modules/embedDocs.js
in case the reference prop used as resource path is empty or invalid ObjectId, we filter those invalid references to avoid a crash later when fetching the object in DB
> filter empty/invalid id reference when embeding docs

- services/docs/lib/services/document.js
error was never catched => could crash api
> reject error instead of throwing it on document creation

- services/stripe-billing/lib/index.js
https://stripe.com/docs/upgrades#2020-08-27
> The tax_ids property on Customers is no longer included by default. You can expand the list but for performance reasons we recommended against doing so unless needed.
- add tax_ids as expand on create/retrieve/update for customers
> stripe API update from 2019-08-14 to 2020-08-27 version

- package-lock.json
- package.json
- services/stripe-billing/lib/index.js
Checks if coupon or promotion code is valid, and return it
I've also updated stripe to its latest version, because promotion codes resource was not available on versions lower than 8.83.0
all checks have been done following this migration guide: https://github.com/stripe/stripe-node/wiki/Migration-guide-for-v8 and payment end-to-end tests have been run successfully
> stripe: check code validity and version updated

- package.json
- services/assets/lib/storages/s3.js
- services/auth/lib/modules/queryBuilder.js
I kept getting warnings about updating uuid. The thing is, we don't need it anymore since we can natively generate uuid since node 14.17.0 => this PR
> refactor: remove uuid dependency

- services/versioned-docs/lib/services/document.js
- check revision on version creation: we shouldn't be able to publish a revision older than the last version revision
- fix the revFilter missing _id when querying on current collection
> fix: check revision on version creation & revFilter incomplete

- lib/middlewares/json-validator.js
- lib/server.js
- package-lock.json
- package.json
Adding the [json-validator middleware](https://github.com/simonplend/express-json-validator-middleware) will enable us to validate request using json schema with ease.
> Add json-validator middleware

- lib/server.js
- package-lock.json
- package.json
As discussed internally, it would be nice to have a logger directly built-in in campsi. [pino](https://getpino.io/#/) is currently the fastest Node.js logger.
I tweaked the default options we pass to pino to fit our workflow.
> Add http logger

- services/docs/lib/param.js
- services/versioned-docs/lib/param.js
I need to "fake" docs service `attachResource` in caas-api to avoid code duplication. That's all
> refactor: docs service attachResource refactored for external usage

- services/docs/lib/handlers.js
- services/versioned-docs/lib/handlers.js
The main purpose of this PR is to rename event emitted by docs.patch to handle this specific case (i don't want to handle it the same way as put events). I've also added the original document data to the emitted payload since I need it to check what's been unset, if any 
I also renamed all versioned docs service events because they had the same name as docs service events.
> refactor: patched event renamed for more precise usage

- services/stripe-billing/lib/index.js
refactored due to linter, but the thing is, `this` ends up being undefined.
2 ways of fixing it:
- bind this when this function is called, but I don't like this, feels like outdated way of using javascript
- use an arrow function => the fix I've chosen
> fix: check coupon code validity wrongly refactored

- package-lock.json
- package.json
- services/assets/package-lock.json
- services/assets/package.json
Goal of this PR is to fix the security alerts of the dependancies as reported by github. The same report can be found by running npm audit from the command line.
To fix these issues I ran npm audit fix which self corrected all of the non breaking issues.
All the unit tests still run and other members of the team have tested this version with CaasStyleGuide to check that multer is not causing any issues.
> udpated dependencies to fix vulnerbalities

- lib/modules/buildLink.js
- lib/modules/buildSingleDocumentLink.js
- services/docs/lib/handlers.js
Goal of this PR is to fix the buldLink test that was failing due to multiple functions being exported from the same file. buildLink is now the default export and exisiting functionality should be preserved
> buildLink default export from buildLinks file

- services/auth/lib/local.js
Actually if user not exist in forget-password, campsi return an error. I changed the behaviour and now campsi always return success even if the user don't exist.
Like this no one can try one by one email.
> [CAMPSI-MONO] - Don't response an error if user not create

- services/stripe-billing/lib/index.js
https://github.com/stripe/stripe-node#network-retries
considered as good practice by stripe to avoid object lock timeout: https://stripe.com/docs/rate-limits#object-lock-timeouts
> This object cannot be accessed right now because another API request or Stripe process is currently accessing it. If you see this error intermittently, retry the request. If you see this error frequently and are making multiple concurrent requests to a single object, make your requests serially or at a lower rate.
> feat: stripe maxNetworkRetries set

- services/docs/lib/modules/queryBuilder.js
- services/docs/lib/services/document.js
When declaring resource, you can add virtual properties, for instance:
```javascript
organizations: {
label: 'organization',
class: 'entry',
schema: { $ref: 'vault/organization.schema.json' },
virtualProperties: {
emailDomain: orga => orga.email?.split('@').pop()
}
},
```
virtual properties are computed on GET and removed (if presents) on POST/PUT/PATCH
> feat: handle virtual properties for docs service

- lib/server.js
The goal of the PR was to reduce the noise produced by pinoHttp when running tests, especially tests that were mean't to fail. The default level has been set to silent. This can be overriden by creating a pino object in the service configuration file with the appropriate options set.
> set default pinoHttp log level to silent

- services/docs/lib/handlers.js
- services/docs/lib/param.js
- services/docs/lib/services/document.js
- test/docs/lock-document.js
Goal of this PR was to allow admins to delete locks on a document that belonged to other users. A non admin user should not be able to delete  a lock that belongs to someone else.
> feat: delete any document lock if admin

- services/docs/lib/index.js
- services/notifications/index.js
Fairly self explanatory - Ajv's strict mode has been turned off so that there aren't loads of warning messages on the screen / in the logs at run time. AJV Errors will still cause the API to fail.
> fix: turn off strict mode in AJV

- README.md
- docker-compose.yml
In this pr, we add the possibility of being able to use docker to launch campsi-mono locally, avoiding the installation of mongoDB as well as version / architecture conflicts.
- create a docker compose file with mongo 5.0.9 Community
- add the run command in the readme
> add a docker-compose.yml

- services/auth/lib/local.js
- services/docs/lib/services/document.js
- test/auth/auth-fetch-users.js
- test/auth/auth-local-passwordRegex.js
- test/config/test.js
In this feat, we add a new password regexp option in the auth service.
The routes concerned are : 
- signup
- reset-password
- updatePassword
btw, a verification of the email field has been added
Tested locally with caas-api & caas-styleguide
Doc updated
> Dev 2125 feat/add password regex option

- package-lock.json
- services/docs/lib/modules/embedDocs.js
title self-explanatory 
I only changed that:
`const subDocument = { _id: new ObjectId(reference) };`
the other diff is linter and update of `"eslint-config-axeptio": "^1.0.0",`
btw: forcing double quotes is 🤮, but it's my personal taste
> fix: subdocument _id missing

- test/auth/auth-local.js
It was reported that on signup it was possible to create an account with an existing email if the case was different. 
I added a test case to test this hypothesis and tested manually from the front end, it does not appear possible to do this anymore.
The CODE in the PR is an additional test to signup with a an existing user email in a different case (it is supposed to fail)
> As a developer, I want to check email account uniqueness

- lib/modules/paginateCursor.js
In the `paginateCursor()` function, there is a treatment for classic cursors and cursors resulting from an aggregation.
And unfortunately there is an oversight in the application of the pagination on the cursors resulting from an aggregation.
So I add it in this fix
> fix: paging systems with agregation cursor

- services/stripe-billing/lib/index.js
- test/stripe-billing/test.js
self explanatory - allow use of the plus symbol (+) in the first part of an email address before the '@'
> fix: allow + in email address

- package-lock.json
- services/stripe-billing/lib/index.js
To avoid creating a stripe resource multiple time (in case of retry or anything like that), we will use an idempotency key on some POST API calls. This key is a hash built with stripe params, stripe method, and the current timestamp in seconds, to avoid recreating this resource within the same second. 
Don't hesitate if you think a second is not enough
> feat: add idempotency key to some stripe API calls (DEV-2556)

- .github/workflows/release-package.yml
Semantic-release needs node 18 to run since 2 days ago otherwise it fails and therefore the npm version doesn't update automatically.
This should not impact the node version used by campsi.
> fix: update semantic release node version to 18

- services/docs/lib/services/document.js
PR fixes an issue whereby the field names extracted from incoming user query to be used in sort filter where not being correctly assembled causing the sort option to not be taken into account. 
The same issue was causing the with=creator option to cause mongodb to reject the query and cause an error
> handle cases of reverse triage

- test/docs/pagination.js
This PR adds two tests one that does retrieves a test data set in sorted order and the other that retrieves the test data set sorted in reverse order.
The data set contains 100 entries (pizza_0 to pizza_99).
The last 5 and first 5 entries of the returned data sets are examined to make sure they are in the right order.
> feat: add unit tests for sort

- services/docs/lib/index.js
This PR changes the comments tagged as ignore = true to ignore = always if the route is never to be excluded from the swagger autogen process. This was only needed for the route '/' which clashes if there are several endpoints overriding the docs service as is the case in caas-api for example
> Dev 2977 change swagger comments in doc service

- lib/modules/paginateCursor.js
- services/assets/lib/services/asset.js
- services/docs/lib/handlers.js
- services/docs/lib/services/document.js
- services/versioned-docs/lib/services/document.js
pagination was previously using `paginateCursor`, which basically execute the query to get the number of documents (now that `cursor.count()` is deprecated), then rewind the cursor, apply skip/limit/sort and execute the query once again.
That's not very efficient and can be slow, especially when the number of documents is huge. 
I've refactored it to use `countDocuments` (when possible) instead, and removed old promise syntax too.
Unit tests results all green
> feat: refactor paginate cursor for better efficiency (DEV-3089)

- services/auth/lib/handlers.js
- services/auth/lib/index.js
- services/auth/lib/local.js
- services/auth/lib/passportMiddleware.js
- services/auth/lib/tokens.js
in passport proxy callback middleware:
- user doesn't exists: we create it
- user exists, has one identity, but not the one we are trying to login with: we return an error with the provider the provider the user should login with
- user exists and has multiple identities: we update it by removing the other ones, to keep only the one the user is trying to login with. we also remove related tokens
- user exists, but has no identities (for instance: invitation): we update it
- user exists, has only one identity: the one we are trying to login with: we update it too
Also: `deleteExpiredTokens` refactored/cleaned up
> fix: disable multiple identity providers for the same user (DEV-3353)

- package-lock.json
- package.json
- services/auth/lib/handlers.js
DEV-3511
In this PR, we add a new exportable function.
The function checks if an email address belongs to a disposable email domain.
In another issue, we will integrate this function in the auth service.
Tested locally
> Dev 3511 improvement/add disposable email domains

- services/auth/lib/handlers.js
- services/auth/lib/local.js
- services/stripe-billing/lib/index.js
In this PR, we just centralize the regex present in campsi-mono in an exportable function
> fix: add a common regex for mail verification and add a todo

- services/auth/lib/handlers.js
- services/auth/lib/passportMiddleware.js
For now, invitation token is not stored in db when an invitation is sent to an already existing user
Thus, this invitation can't be accepted.
This PR fixes this.
> feat: add/validate invitation on existing user (DEV-3664)

- services/auth/lib/local.js
Til now, an existing user without any providers (=> created through invitation), could not signup without using the invitation signup form.
This PR fixes that. (Tested)
> fix: user local signup with existing invitations (DEV-3677)

- lib/modules/sanitize.js
- package-lock.json
- package.json
- services/auth/lib/handlers.js
- services/docs/lib/modules/queryBuilder.js
- services/versioned-docs/lib/modules/queryBuilder.js
In this PR, we add an HTML-sanitizer in post/put/patch docs and versioned-docs endpoint to prevent XSS injection.
Do to this, we use https://www.npmjs.com/package/sanitize-html library.
I tested `sanitizeHTMLFromXSS()` by applying it on the GET endpoints of our api, then I did several tests on the BO.
> Dev 3736 improvement/xss protection

- services/auth/lib/handlers.js
- services/auth/lib/modules/queryBuilder.js
- test/auth/auth-local-password-reset.js
- test/auth/auth-local-passwordRegex.js
- test/auth/auth-local.js
- test/auth/auth.js
- test/auth/delete.js
- test/docs/events.js
- test/docs/soft-delete.js
title self-explanatory (we don't use `user.token` anymore)
all auth unit tests are green and have been fixed
Note: I've fixed auth unit tests, and some tests of docs service, but some more are broken.
Since they're unrelated to this issue, I've created [another issue](https://linear.app/axeptio/issue/DEV-3979/fix-campsi-broken-unit-tests), for later
> chore: remove token singular references (DEV-3525)

- package-lock.json
- package.json
- services/audit/index.js
- services/docs/lib/handlers.js
- services/docs/lib/index.js
- services/docs/lib/modules/queryBuilder.js
- services/docs/lib/services/document.js
- services/notifications/index.js
- services/versioned-docs/lib/index.js
patch requests only validate the payload, not the whole document data. But some validations may depend on other props, for instance this in JSON schema spec won't work if only one of these 2 props is passed:
```JSON
"allOf": [
{
"not": {
"required": ["marketplace", "organizationId"]
}
}
]
```
Note: added `ajv-errors` package to allow custom error messages in JSON schema specs
> fix: patch requests only validate the payload (DEV-4094)

- services/docs/lib/index.js
self-explanatory
this feature allows injecting additional middlewares per resource per HTTP method
```javascript
{
additionalMiddlewares: {
POST: async (req, res, next) => { // do stuff },
PUT: async (req, res, next) => { // do stuff },
}
> feat: additional middlewares per resource/method (DEV-5161)

- services/docs/lib/modules/queryBuilder.js
This bug can occur when the value to patch is an array
> fix: trying to redefine non-empty obj

- services/stripe-billing/lib/index.js
Lots of stuff due to the deprecation of SEPA Debit Sources in favor of SEPA Debit Payment Method
- list all customer's payment methods
- attach a payment method to a customer
- patch a payment_method
- setup_intent creation improved
- payment_intent related routes updated
> feat: improve payment_method usage

- services/docs/lib/modules/queryBuilder.js
- test/docs/validation.js
to avoid this kind of error:
```json
{
"message":"Trying to redefine non-empty obj['default_payment_method']",
"stack":["Error: Trying to redefine non-empty obj['default_payment_method']","    at DotObject._fill (C:\\Users\\roro\\Documents\\Agilitation\\DevProjects\\caas-api\\node_modules\\dot-object\\index.js:118:15)","    at DotObject._fill (C:\\Users\\roro\\Documents\\Agilitation\\DevProjects\\caas-api\\node_modules\\dot-object\\index.js:114:10)","    at DotObject._fill (C:\\Users\\roro\\Documents\\Agilitation\\DevProjects\\caas-api\\node_modules\\dot-object\\index.js:114:10)","    at DotObject.str (C:\\Users\\roro\\Documents\\Agilitation\\DevProjects\\caas-api\\node_modules\\dot-object\\index.js:179:10)","    at Function.str (C:\\Users\\roro\\Documents\\Agilitation\\DevProjects\\caas-a …
```
> fix: patching whole object

- services/auth/lib/handlers.js
- services/auth/lib/index.js
> fix: (not for production) add a delete endpoint for deleting the current user.

- README.md
- lib/middlewares/rateLimit.js
- lib/modules/responseHelpers.js
- lib/server.js
- package-lock.json
- package.json
- services/auth/lib/defaults.js
- services/auth/lib/handlers.js
- services/auth/lib/index.js
- services/auth/lib/local.js
Add two types of rate limit to the local auth endpoints - a general rate limit for all APIs and also a password failure rate limit on the signin endpoint
Rate limits are implemented via redis.
> feat: rate limit local auth endpoints

- lib/middlewares/rateLimit.js
- services/auth/lib/handlers.js
- services/auth/lib/local.js
Fix: allow configuration to enable the rate limit logic to be skipped, e.g. from unit tests.  Configure an ignore header and value.
> Fix: allow configuration to enable the rate limit logic to be skipped.
